### ISSUE TITLE
Explanation of how this works ?

### ISSUE THREAD

**Issue by dispix** [burakcan/mb#21]
Hi,

Just discovered the library and was wondering if you could provide an explanation for those of us who are lost by the syntax ? It's always great to learn something new about javascript 😄

**Comment by akre54** [comment]
Sure. Expanded out a bit...
```js
var mb=p=>o=>p.map(c=>o=(o||{})[c])&&o
```
Becomes:
```js
function mb(p) {
  return function(o) {
    return p.map(function(c) {
      o = (o || {})[c];
      return o;
    }) && o;
  }
}
```
Basically it's taking a list of strings and iterating through the list, each time reassigning `o` as `o[c]` and finally returning `o`.

This is called a higher-order function, because the first function takes a path array `p` and returns a function that can be called with your object `o`. You can reuse the returned function to pass in different `o` object arguments.

The `||` guards against an undefined `o`, so if the property `c` (i.e. one of the strings in the path array `p`) exists in `o`, it will return the value for that key `c`, otherwise will return `undefined`.

**Comment by dispix** [comment]
So I was ok with the currying and the mapping over the path but what I don't understand is the `o = (o || {})[c]` bit. How is it safe to do that without modifying the original object ?

Edit: moreover, the `.map` method returns an array so I would have expected a `.reduce` here. How do you not end up with an array when returning the result of `p.map` ?

Edit 2: nevermind about the first edit, this is done by the `&&o` bit.

**Comment by akre54** [comment]
> How is it safe to do that without modifying the original object ?

It doesn't modify the original object because the `o` is an argument and can be reassigned.

Objects in JS are pass-by-reference so if you mutated `o` it would affect the outer (calling) function's copy of `o`, but in this case we aren't mutating.

**Comment by dispix** [comment]
So you're reassigning the argument with the result of every iteration of the `map` method and return the argument instead of the result of the `map` method. I guess you use `map` instead of `forEach` because it's shorter. I never had to reassign a function argument (and I guess in most use cases it is considered a bad practice) so that's what confused me here.

Thanks for the explanation 😄

**Comment by burakcan** [comment]
> I guess you use map instead of forEach because it's shorter.

correct :)

> I never had to reassign a function argument (and I guess in most use cases it is considered a bad practice) so that's what confused me here.

It is (can be) a bad practice, but again it's the shortest possible way to keep an accumulator.

**Comment by burakcan** [comment]
And there's another explanation here by @FranciscoG: https://gist.github.com/FranciscoG/18f000abd514d63835976c1df3d7e0c4
